#### general settings
name: 001_RRDB_MSRResNetx4x8_disph
use_tb_logger: true
model: sr
distortion: sr
scale: 4
gpu_ids: [9]

#### datasets
datasets:
  train:
    name: disph_train
    mode: LQGT
    dataroot_GT: ../datasets/disph_train_sub

    use_shuffle: true
    n_workers: 2  # per GPU
    batch_size: 64
    GT_size: 128
    use_flip: true
    use_rot: False
    color: EXR
  val:
    name: disph_val
    mode: LQGT
    dataroot_GT: ../datasets/disph_val

#### network structures
network_G:
  which_model_G: MSRResNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 16
  upscale: 4

#### path
path:
  pretrain_model_G: /mount/ForRuilong/SRData/MSRResNetx4.pth
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 1000000
  warmup_iter: -1  # no warm up
  T_period: [250000, 250000, 250000, 250000]
  restarts: [250000, 500000, 750000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3

